### ISSUE TITLE
distutils.errors.CompileError when installing textpipe

### ISSUE THREAD

**Issue by rajbala** [textpipe/textpipe#152]
I get the following error when I try to install textpipe using Python 3.6.8 and Ubuntu 18.04.  

Any thoughts?  I can't seem to find any helpful solutions on the interwebs.

> Traceback (most recent call last):
>       File "/usr/lib/python3.6/distutils/unixccompiler.py", line 118, in _compile
>         extra_postargs)
>       File "/usr/lib/python3.6/distutils/ccompiler.py", line 909, in spawn
>         spawn(cmd, dry_run=self.dry_run)
>       File "/usr/lib/python3.6/distutils/spawn.py", line 36, in spawn
>         _spawn_posix(cmd, search_path, dry_run=dry_run)
>       File "/usr/lib/python3.6/distutils/spawn.py", line 159, in _spawn_posix
>         % (cmd, exit_status))
>     distutils.errors.DistutilsExecError: command 'x86_64-linux-gnu-gcc' failed with exit status 1
>     
>     During handling of the above exception, another exception occurred:
>     
>     Traceback (most recent call last):
>       File "/tmp/pip-build-8bvewwgk/cld2-cffi/.eggs/cffi-1.12.3-py3.6-linux-x86_64.egg/cffi/ffiplatform.py", line 51, in _build
>         dist.run_command('build_ext')
>       File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
>         cmd_obj.run()
>       File "/usr/lib/python3/dist-packages/setuptools/command/build_ext.py", line 78, in run
>         _build_ext.run(self)
>       File "/usr/lib/python3.6/distutils/command/build_ext.py", line 339, in run
>         self.build_extensions()
>       File "/usr/lib/python3.6/distutils/command/build_ext.py", line 448, in build_extensions
>         self._build_extensions_serial()
>       File "/usr/lib/python3.6/distutils/command/build_ext.py", line 473, in _build_extensions_serial
>         self.build_extension(ext)
>       File "/usr/lib/python3/dist-packages/setuptools/command/build_ext.py", line 199, in build_extension
>         _build_ext.build_extension(self, ext)
>       File "/usr/lib/python3.6/distutils/command/build_ext.py", line 533, in build_extension
>         depends=ext.depends)
>       File "/usr/lib/python3.6/distutils/ccompiler.py", line 574, in compile
>         self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
>       File "/usr/lib/python3.6/distutils/unixccompiler.py", line 120, in _compile
>         raise CompileError(msg)
>     distutils.errors.CompileError: command 'x86_64-linux-gnu-gcc' failed with exit status 1
>     
>     During handling of the above exception, another exception occurred:
>     
>     Traceback (most recent call last):
>       File "<string>", line 1, in <module>
>       File "/tmp/pip-build-8bvewwgk/cld2-cffi/setup.py", line 191, in <module>
>         'Topic :: Text Processing :: Linguistic'
>       File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 129, in setup
>         return distutils.core.setup(**attrs)
>       File "/usr/lib/python3.6/distutils/core.py", line 148, in setup
>         dist.run_commands()
>       File "/usr/lib/python3.6/distutils/dist.py", line 955, in run_commands
>         self.run_command(cmd)
>       File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
>         cmd_obj.run()
>       File "/usr/lib/python3/dist-packages/setuptools/command/egg_info.py", line 278, in run
>         self.find_sources()
>       File "/usr/lib/python3/dist-packages/setuptools/command/egg_info.py", line 293, in find_sources
>         mm.run()
>       File "/usr/lib/python3/dist-packages/setuptools/command/egg_info.py", line 524, in run
>         self.add_defaults()
>       File "/usr/lib/python3/dist-packages/setuptools/command/egg_info.py", line 560, in add_defaults
>         sdist.add_defaults(self)
>       File "/usr/lib/python3/dist-packages/setuptools/command/py36compat.py", line 34, in add_defaults
>         self._add_defaults_python()
>       File "/usr/lib/python3/dist-packages/setuptools/command/sdist.py", line 127, in _add_defaults_python
>         build_py = self.get_finalized_command('build_py')
>       File "/usr/lib/python3.6/distutils/cmd.py", line 299, in get_finalized_command
>         cmd_obj.ensure_finalized()
>       File "/usr/lib/python3.6/distutils/cmd.py", line 107, in ensure_finalized
>         self.finalize_options()
>       File "/usr/lib/python3/dist-packages/setuptools/command/build_py.py", line 34, in finalize_options
>         orig.build_py.finalize_options(self)
>       File "/usr/lib/python3.6/distutils/command/build_py.py", line 45, in finalize_options
>         ('force', 'force'))
>       File "/usr/lib/python3.6/distutils/cmd.py", line 287, in set_undefined_options
>         src_cmd_obj.ensure_finalized()
>       File "/usr/lib/python3.6/distutils/cmd.py", line 107, in ensure_finalized
>         self.finalize_options()
>       File "/tmp/pip-build-8bvewwgk/cld2-cffi/setup.py", line 143, in finalize_options
>         self.distribution.ext_modules = get_ext_modules()
>       File "/tmp/pip-build-8bvewwgk/cld2-cffi/setup.py", line 128, in get_ext_modules
>         import cld2
>       File "/tmp/pip-build-8bvewwgk/cld2-cffi/cld2/__init__.py", line 190, in <module>
>         extra_compile_args=_COMPILER_ARGS)
>       File "/tmp/pip-build-8bvewwgk/cld2-cffi/.eggs/cffi-1.12.3-py3.6-linux-x86_64.egg/cffi/api.py", line 464, in verify
>         lib = self.verifier.load_library()
>       File "/tmp/pip-build-8bvewwgk/cld2-cffi/.eggs/cffi-1.12.3-py3.6-linux-x86_64.egg/cffi/verifier.py", line 104, in load_library
>         self._compile_module()
>       File "/tmp/pip-build-8bvewwgk/cld2-cffi/.eggs/cffi-1.12.3-py3.6-linux-x86_64.egg/cffi/verifier.py", line 201, in _compile_module
>         outputfilename = ffiplatform.compile(tmpdir, self.get_extension())
>       File "/tmp/pip-build-8bvewwgk/cld2-cffi/.eggs/cffi-1.12.3-py3.6-linux-x86_64.egg/cffi/ffiplatform.py", line 22, in compile
>         outputfilename = _build(tmpdir, ext, compiler_verbose, debug)
>       File "/tmp/pip-build-8bvewwgk/cld2-cffi/.eggs/cffi-1.12.3-py3.6-linux-x86_64.egg/cffi/ffiplatform.py", line 58, in _build
>         raise VerificationError('%s: %s' % (e.__class__.__name__, e))
>     cffi.VerificationError: CompileError: command 'x86_64-linux-gnu-gcc' failed with exit status 1
>     
>     ----------------------------------------
> Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-8bvewwgk/cld2-cffi/

**Comment by VascoVisser** [comment]
Is this the whole error? Seems like the important part of the error is missing.

Do you have the `build-essential` and `libffi-dev` packages installed with apt? You might need to compile with `-Wno-narrowing`, i.e.:
```
~$ CFLAGS="-Wno-narrowing" pip install textpipe
```

**Comment by rajbala** [comment]
I do indeed have those other packages installed.  I tried compiling with what you posted, but got the same result.  

Here's additional information that was logged before the stacktrace:


> Collecting textpipe
>   Downloading https://files.pythonhosted.org/packages/5f/9b/4682a4ed5a7aea6734f25cb9f14d1e5d2851b1ab4b99e3b58adc48197a7a/textpipe-0.10.1.tar.gz
> Collecting beautifulsoup4~=4.7 (from textpipe)
>   Downloading https://files.pythonhosted.org/packages/1d/5d/3260694a59df0ec52f8b4883f5d23b130bc237602a1411fa670eae12351e/beautifulsoup4-4.7.1-py3-none-any.whl (94kB)
>     100% |████████████████████████████████| 102kB 6.3MB/s 
> Collecting cld2_cffi~=0.1 (from textpipe)
>   Downloading https://files.pythonhosted.org/packages/52/6d/044789e730141bcda2a7368836f714684a7d13bd44a2a33b387cb31b4335/cld2-cffi-0.1.4.tar.gz (17.6MB)
>     100% |████████████████████████████████| 17.6MB 86kB/s 
>     Complete output from command python setup.py egg_info:
>     warning: no previously-included files found matching 'setup.pyc'
>     warning: no previously-included files matching 'yacctab.*' found under directory 'tests'
>     warning: no previously-included files matching 'lextab.*' found under directory 'tests'
>     warning: no previously-included files matching 'yacctab.*' found under directory 'examples'
>     warning: no previously-included files matching 'lextab.*' found under directory 'examples'
>     zip_safe flag not set; analyzing archive contents...
>     pycparser.ply.__pycache__.lex.cpython-36: module references __file__
>     pycparser.ply.__pycache__.lex.cpython-36: module MAY be using inspect.getsourcefile
>     pycparser.ply.__pycache__.yacc.cpython-36: module references __file__
>     pycparser.ply.__pycache__.yacc.cpython-36: module MAY be using inspect.getsourcefile
>     pycparser.ply.__pycache__.yacc.cpython-36: module MAY be using inspect.stack
>     pycparser.ply.__pycache__.ygen.cpython-36: module references __file__
>     
>     Installed /tmp/pip-build-z5rg3zfl/cld2-cffi/.eggs/pycparser-2.19-py3.6.egg
>     running egg_info
>     creating pip-egg-info/cld2_cffi.egg-info
>     writing pip-egg-info/cld2_cffi.egg-info/PKG-INFO
>     writing dependency_links to pip-egg-info/cld2_cffi.egg-info/dependency_links.txt
>     writing requirements to pip-egg-info/cld2_cffi.egg-info/requires.txt
>     writing top-level names to pip-egg-info/cld2_cffi.egg-info/top_level.txt
>     writing manifest file 'pip-egg-info/cld2_cffi.egg-info/SOURCES.txt'
>     cld2/binding.cc: In function ‘int cld_detect(char*, int, cld_results_t*, const char*, const char*, const char*, const char*, int, int, int, int, int, int, int, int, int)’:
>     cld2/binding.cc:165:41: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
>                      for (unsigned int i=0; i<num_chunks; i++) {
>                                             ~^~~~~~~~~~~
>     cld2/internal/compact_lang_det_hint_code.cc: In function ‘std::__cxx11::string CLD2::TrimCLDLangTagsHint(const string&)’:
>     cld2/internal/compact_lang_det_hint_code.cc:1060:15: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
>          if (comma == string::npos) {comma = langtags.size();} // fake trailing comma
>              ~~~~~~^~~~~~~~~
>     cld2/internal/compact_lang_det_hint_code.cc: In function ‘void CLD2::SetCLDLangTagsHint(const string&, CLD2::CLDLangPriors*)’:
>     cld2/internal/compact_lang_det_hint_code.cc:1403:15: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
>          if (comma == string::npos) {comma = langtags.size();} // fake trailing comma
>              ~~~~~~^~~~~~~~~
>     cld2/internal/compact_lang_det_impl.cc: In function ‘void CLD2::CalcSummaryLang(CLD2::DocTote*, int, const int*, const CLD2::Language*, const int*, CLD2::Language*, bool*, bool, bool, int)’:
>     cld2/internal/compact_lang_det_impl.cc:1455:7: warning: unused variable ‘plang_second’ [-Wunused-variable]
>        int plang_second = PerScriptNumber(ULScript_Latin, language3[active_slot[1]]);
>            ^~~~~~~~~~~~
>     cld2/internal/compact_lang_det_impl.cc: In function ‘CLD2::Language CLD2::DetectLanguageSummaryV2(const char*, int, bool, const CLD2::CLDHints*, bool, int, CLD2::Language, CLD2::Language*, int*, double*, CLD2::ResultChunkVector*, int*, bool*)’:
>     cld2/internal/compact_lang_det_impl.cc:1849:14: warning: unused variable ‘ulscript’ [-Wunused-variable]
>          ULScript ulscript = scriptspan.ulscript;
>                   ^~~~~~~~
>     cld2/internal/compact_lang_det_impl.cc:1788:7: warning: unused variable ‘next_other_tote’ [-Wunused-variable]
>        int next_other_tote = 2;
>            ^~~~~~~~~~~~~~~
>     cld2/internal/compact_lang_det_impl.cc:1789:7: warning: unused variable ‘tote_num’ [-Wunused-variable]
>        int tote_num = 0;
>            ^~~~~~~~
>     cld2/internal/compact_lang_det_impl.cc:1793:8: warning: unused variable ‘tote_seen’ [-Wunused-variable]
>        bool tote_seen[4] = {false, false, false, false};
>             ^~~~~~~~~
>     cld2/internal/compact_lang_det_impl.cc:1794:7: warning: unused variable ‘tote_grams’ [-Wunused-variable]
>        int tote_grams[4] = {0, 0, 0, 0};     // Number in partial chunk
>            ^~~~~~~~~~
>     cld2/internal/compact_lang_det_impl.cc:1795:12: warning: unused variable ‘tote_script’ [-Wunused-variable]
>        ULScript tote_script[4] =
>                 ^~~~~~~~~~~
>     cld2/internal/compact_lang_det_impl.cc:1814:7: warning: unused variable ‘advance_by’ [-Wunused-variable]
>        int advance_by = 2;                   // Advance 2 bytes
>            ^~~~~~~~~~
>     cld2/internal/compact_lang_det_impl.cc:1815:7: warning: unused variable ‘advance_limit’ [-Wunused-variable]
>        int advance_limit = textlimit >> 3;   // For first 1/8 of max document
>            ^~~~~~~~~~~~~
>     cld2/internal/compact_lang_det_impl.cc:1817:7: warning: variable ‘initial_word_span’ set but not used [-Wunused-but-set-variable]
>        int initial_word_span = kDefaultWordSpan;
>            ^~~~~~~~~~~~~~~~~
>     cld2/internal/compact_lang_det_impl.cc:1828:7: warning: unused variable ‘chunksizeunis’ [-Wunused-variable]
>        int chunksizeunis = (chunksizequads * 5) >> 1;
>            ^~~~~~~~~~~~~
>     cld2/internal/compact_lang_det_impl.cc:1832:7: warning: unused variable ‘spantooshortlimit’ [-Wunused-variable]
>        int spantooshortlimit = kShortSpanThresh;
>            ^~~~~~~~~~~~~~~~~
>     cld2/internal/offsetmap.cc: In member function ‘void CLD2::OffsetMap::Printmap(const char*)’:
>     cld2/internal/offsetmap.cc:84:54: warning: array subscript has type ‘char’ [-Wchar-subscripts]
>          fprintf(fout, "%c%02d ", "&=+-"[OpPart(diffs_[i])], LenPart(diffs_[i]));
>                                                           ^
>     cld2/internal/offsetmap.cc: In member function ‘void CLD2::OffsetMap::DumpString()’:
>     cld2/internal/offsetmap.cc:210:56: warning: array subscript has type ‘char’ [-Wchar-subscripts]
>          fprintf(stderr, "%c%02d ", "&=+-"[OpPart(diffs_[i])], LenPart(diffs_[i]));
>                                                             ^
>     cld2/internal/offsetmap.cc: In member function ‘bool CLD2::OffsetMap::MoveLeft()’:
>     cld2/internal/offsetmap.cc:404:8: warning: variable ‘retval’ set but not used [-Wunused-but-set-variable]
>        bool retval = true;
>             ^~~~~~
>     cld2/internal/offsetmap.cc: In static member function ‘static bool CLD2::OffsetMap::CopyInserts(CLD2::OffsetMap*, CLD2::OffsetMap*)’:
>     cld2/internal/offsetmap.cc:484:40: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
>        while (ok && (source->next_diff_sub_ != source->diffs_.size())) {
>                      ~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~
>     cld2/internal/offsetmap.cc: In static member function ‘static bool CLD2::OffsetMap::CopyDeletes(CLD2::OffsetMap*, CLD2::OffsetMap*)’:
>     cld2/internal/offsetmap.cc:498:40: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
>        while (ok && (source->next_diff_sub_ != source->diffs_.size())) {
>                      ~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~
>     cld2/internal/scoreonescriptspan.cc: In function ‘void CLD2::ScoreEntireScriptSpan(const CLD2::LangSpan&, CLD2::ScoringContext*, CLD2::DocTote*, CLD2::ResultChunkVector*)’:
>     cld2/internal/scoreonescriptspan.cc:1149:5: warning: narrowing conversion of ‘score’ from ‘int’ to ‘CLD2::uint16 {aka short unsigned int}’ inside { } [-Wnarrowing]
>          };
>          ^
>     cld2/internal/scoreonescriptspan.cc:1149:5: warning: narrowing conversion of ‘bytes’ from ‘int’ to ‘CLD2::uint16 {aka short unsigned int}’ inside { } [-Wnarrowing]
>     cld2/internal/scoreonescriptspan.cc:1149:5: warning: narrowing conversion of ‘reliability’ from ‘int’ to ‘CLD2::uint8 {aka unsigned char}’ inside { } [-Wnarrowing]
>     cld2/internal/scoreonescriptspan.cc:1149:5: warning: narrowing conversion of ‘reliability’ from ‘int’ to ‘CLD2::uint8 {aka unsigned char}’ inside { } [-Wnarrowing]
>     cld2/internal/utf8statetable.cc: In function ‘int CLD2::UTF8GenericReplaceInternalTwoByte(const UTF8ReplaceObj_2*, const StringPiece&, StringPiece&, bool, int*, int*, int*, CLD2::OffsetMap*)’:
>     cld2/internal/utf8statetable.cc:933:7: warning: variable ‘src_lll’ set but not used [-Wunused-but-set-variable]
>        int src_lll = srclimit - src;
>            ^~~~~~~
>     cld2/internal/utf8statetable.cc:934:7: warning: variable ‘dst_lll’ set but not used [-Wunused-but-set-variable]
>        int dst_lll = dstlimit - dst;
>            ^~~~~~~
>     cld2/internal/utf8statetable.cc: At global scope:
>     cld2/internal/utf8statetable.cc:200:13: warning: ‘bool CLD2::IsReplaceObj_2(const CLD2::UTF8StateMachineObj_2&)’ defined but not used [-Wunused-function]
>      static bool IsReplaceObj_2(const UTF8StateMachineObj_2& obj) {
>                  ^~~~~~~~~~~~~~
>     cld2/internal/utf8statetable.cc:194:13: warning: ‘bool CLD2::IsReplaceObj(const CLD2::UTF8StateMachineObj&)’ defined but not used [-Wunused-function]
>      static bool IsReplaceObj(const UTF8StateMachineObj& obj) {
>                  ^~~~~~~~~~~~
>     cld2/internal/utf8statetable.cc:189:13: warning: ‘bool CLD2::IsScanObj(const CLD2::UTF8StateMachineObj&)’ defined but not used [-Wunused-function]
>      static bool IsScanObj(const UTF8StateMachineObj& obj) {
>                  ^~~~~~~~~
>     cld2/internal/utf8statetable.cc:184:13: warning: ‘bool CLD2::IsPropObj_2(const CLD2::UTF8StateMachineObj_2&)’ defined but not used [-Wunused-function]
>      static bool IsPropObj_2(const UTF8StateMachineObj_2& obj) {
>                  ^~~~~~~~~~~
>     cld2/internal/utf8statetable.cc:179:13: warning: ‘bool CLD2::IsPropObj(const CLD2::UTF8StateMachineObj&)’ defined but not used [-Wunused-function]
>      static bool IsPropObj(const UTF8StateMachineObj& obj) {
>                  ^~~~~~~~~
>     cld2/internal/cld_generated_cjk_uni_prop_80.cc:7089:1: error: narrowing conversion of ‘-14’ from ‘int’ to ‘CLD2::uint8 {aka unsigned char}’ inside { } [-Wnarrowing]
>      };
>      ^
>     cld2/internal/cld_generated_cjk_uni_prop_80.cc:7089:1: error: narrowing conversion of ‘-14’ from ‘int’ to ‘CLD2::uint8 {aka unsigned char}’ inside { } [-Wnarrowing]
>     cld2/internal/cld_generated_cjk_uni_prop_80.cc:7089:1: error: narrowing conversion of ‘-14’ from ‘int’ to ‘CLD2::uint8 {aka unsigned char}’ inside { } [-Wnarrowing]
>     cld2/internal/cld_generated_cjk_uni_prop_80.cc:7089:1: error: narrowing conversion of ‘-14’ from ‘int’ to ‘CLD2::uint8 {aka unsigned char}’ inside { } [-Wnarrowing]
>     cld2/internal/cld_generated_cjk_uni_prop_80.cc:7089:1: error: narrowing conversion of ‘-14’ from ‘int’ to ‘CLD2::uint8 {aka unsigned char}’ inside { } [-Wnarrowing]
>     cld2/internal/cld_generated_cjk_uni_prop_80.cc:7089:1: error: narrowing conversion of ‘-14’ from ‘int’ to ‘CLD2::uint8 {aka unsigned char}’ inside { } [-Wnarrowing]
>     cld2/internal/cld_generated_cjk_uni_prop_80.cc:7089:1: error: narrowing conversion of ‘-14’ from ‘int’ to ‘CLD2::uint8 {aka unsigned char}’ inside { } [-Wnarrowing]
>     cld2/internal/cld_generated_cjk_uni_prop_80.cc:7089:1: error: narrowing conversion of ‘-14’ from ‘int’ to ‘CLD2::uint8 {aka unsigned char}’ inside { } [-Wnarrowing]
>     cld2/internal/cld_generated_cjk_uni_prop_80.cc:7089:1: error: narrowing conversion of ‘-14’ from ‘int’ to ‘CLD2::uint8 {aka unsigned char}’ inside { } [-Wnarrowing]
>     cld2/internal/cld_generated_cjk_uni_prop_80.cc:7089:1: error: narrowing conversion of ‘-14’ from ‘int’ to ‘CLD2::uint8 {aka unsigned char}’ inside { } [-Wnarrowing]

**Comment by VascoVisser** [comment]
The error you get is `error: narrowing conversion of` which should be fixed by doing `export CFLAGS="-Wno-narrowing"` before `pip install`.

**Comment by rajbala** [comment]
It works when I use that export but don't use sudo.  Thanks!

**Comment by JosefAssad** [comment]
I'm seeing this same problem on Debian testing in a clean virtualenv.

It's a problem upstream in [cld2-cffi](https://github.com/GregBowyer/cld2-cffi/issues/12).

Would it be a good idea to add a troubleshooting note to the README?
